# Generated by Django 5.2.7 on 2025-11-07 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='failed_login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='lockout_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
