# Generated by Django 5.2.7 on 2025-11-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_auth', '0003_customuser_telegram_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='no number', max_length=15, unique=True),
        ),
    ]
